version: "3.9"
services:
  caching:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/bitnami/redis/data
    ports:
      - "6379:6379"
    user: root

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - caching
    environment:
      - REDIS_HOST=caching
    ports:
      - "3000:3000"
    volumes:
      - ./proto:/usr/src/app/proto
    user: root

  server:
    build: server
    restart: always
    environment:
      PGUSER: user
      PGPASSWORD: password
      PGHOST: db
      PGDATABASE: example
    volumes:
      - ./proto:/usr/src/app/proto
    
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    volumes:
      - ./db:/docker-entrypoint-initdb.d
