version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    volumes:
      - ./db:/docker-entrypoint-initdb.d
 
  server:
    build: server
    restart: always
    environment:
      PGUSER: user
      PGPASSWORD: password
      PGHOST: db
      PGDATABASE: example
    volumes:
      - ./proto:/usr/src/app/proto
  
  client:
    build: client
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./proto:/usr/src/app/proto